defmodule Amauta.Repo.TenantMigrations.SpikeTablon do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_events, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :actor_id, :uuid
      add :action, :text, null: false
      add :subject_type, :text
      add :subject_id, :uuid
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:audit_events, [:subject_type, :subject_id])

    create table(:courses, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:courses, [:slug], name: "courses_unique_slug_index")

    create table(:posts, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "posts_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ), null: false

      add :author_id, :uuid, null: false
    end

    create index(:posts, [:course_id, :inserted_at])

    create table(:role_assignments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :role, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false

      add :course_id,
          references(:courses,
            column: :id,
            name: "role_assignments_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )
    end

    create table(:users, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:posts, prefix: prefix()) do
      modify :author_id,
             references(:users,
               column: :id,
               name: "posts_author_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :nothing
             )
    end

    alter table(:role_assignments, prefix: prefix()) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "role_assignments_user_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    alter table(:users, prefix: prefix()) do
      add :name, :text, null: false
      add :email, :text, null: false
      add :api_token_hash, :binary

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:api_token_hash], name: "users_unique_api_token_hash_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop_if_exists unique_index(:users, [:api_token_hash],
                     name: "users_unique_api_token_hash_index"
                   )

    alter table(:users, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :api_token_hash
      remove :email
      remove :name
    end

    drop constraint(:role_assignments, "role_assignments_course_id_fkey")

    drop constraint(:role_assignments, "role_assignments_user_id_fkey")

    alter table(:role_assignments, prefix: prefix()) do
      modify :user_id, :uuid
    end

    drop constraint(:posts, "posts_author_id_fkey")

    drop constraint(:posts, "posts_course_id_fkey")

    alter table(:posts, prefix: prefix()) do
      modify :author_id, :uuid
    end

    drop table(:users, prefix: prefix())

    drop table(:role_assignments, prefix: prefix())

    drop_if_exists index(:posts, [:course_id, :inserted_at])

    drop table(:posts, prefix: prefix())

    drop_if_exists unique_index(:courses, [:slug], name: "courses_unique_slug_index")

    drop table(:courses, prefix: prefix())

    drop_if_exists index(:audit_events, [:subject_type, :subject_id])

    drop table(:audit_events, prefix: prefix())
  end
end
