import Config

# Configure your database
config :amauta, Amauta.Repo,
  username: System.get_env("DATABASE_USER", "postgres"),
  password: System.get_env("DATABASE_PASSWORD", "postgres"),
  hostname: System.get_env("DATABASE_HOST", "localhost"),
  database: "amauta_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :amauta, AmautaWeb.Endpoint,
  # Bind to 0.0.0.0 to expose the server to the docker host machine.
  # This makes make the service accessible from any network interface.
  # Change to `ip: {127, 0, 0, 1}` to allow access only from the server machine.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "6Q7KReo4Dvp2SXVARgLUXmWQ0PJjjMo3jUn3WhbI+wmVzhYuv6L3+Jbpw+/TKP4b",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:amauta, ~w(--sourcemap=inline --watch)]},
    # --poll: los eventos de archivos no cruzan el bind mount desde Windows (RNF-DEV-004).
    tailwind: {Tailwind, :install_and_run, [:amauta, ~w(--watch --poll)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :amauta, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Todo el correo de desarrollo se captura en Mailpit (RNF-DEV-012).
config :amauta, Amauta.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("SMTP_HOST", "localhost"),
  port: String.to_integer(System.get_env("SMTP_PORT", "1025")),
  ssl: false,
  tls: :never,
  auth: :never

# La vigilancia de archivos usa sondeo: los eventos del sistema de archivos
# no atraviesan de forma confiable el montaje desde Windows (RNF-DEV-004).
config :phoenix_live_reload,
  backend: :fs_poll,
  backend_opts: [interval: 500]

# Inicio de sesión rápido con personas de prueba (RNF-DEV-009).
config :amauta, dev_login: true
