defmodule Amauta.Repo.Migrations.SpikeTablon do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS global")

    create table(:institutions, primary_key: false, prefix: "global") do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :schema_name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:institutions, [:schema_name],
             name: "institutions_unique_schema_name_index",
             prefix: "global"
           )

    create unique_index(:institutions, [:slug],
             name: "institutions_unique_slug_index",
             prefix: "global"
           )
  end

  def down do
    drop_if_exists unique_index(:institutions, [:slug],
                     name: "institutions_unique_slug_index",
                     prefix: "global"
                   )

    drop_if_exists unique_index(:institutions, [:schema_name],
                     name: "institutions_unique_schema_name_index",
                     prefix: "global"
                   )

    drop table(:institutions, prefix: "global")
  end
end
