defmodule AmautaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :amauta

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_amauta_key",
    signing_salt: "E75PCfp5",
    same_site: "Lax"
  ]

  # En los tests en navegador, el sandbox de Ecto viaja en el user agent y
  # cada pedido (y cada LiveView) usa la transacción del test.
  if Application.compile_env(:amauta, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  @doc "Opciones de la cookie de sesión (las usan las pruebas en navegador)."
  def session_options, do: @session_options

  # Sin recargador de código al conectar: el pedido HTTP de la página ya lo
  # pasó, y repetirlo demoraba cada conexión en desarrollo (por el bind
  # mount, ~1,5 s). Los cambios de código recargan la página (live_reload).
  # Es una opción de cada transporte: a nivel del socket se ignora.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      code_reloader: false,
      connect_info: [:user_agent, session: @session_options]
    ],
    longpoll: [
      code_reloader: false,
      connect_info: [:user_agent, session: @session_options]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :amauta,
    gzip: not code_reloading?,
    only: AmautaWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug AmautaWeb.DevCodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :amauta
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug AmautaWeb.Router
end
